### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by krankin** [rosalinekarr/stordly#1]
@rosalinekarr .. 

reviewing your submission, gets the following error: 

```
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (File.Error) could not read file "./priv/static/index.html": no such file or directory
```

Wanted to give you a chance to fix that. 

-Kevin

**Comment by rosalinekarr** [comment]
@krankin, sorry, i changed the port for the application to `3000` so i could proxy phoenix through the react app

can you check it by visiting `http://localhost:3000` instead? or would you prefer that i reassign the ports?

**Comment by krankin** [comment]
port 3000, that got it.  

Thanks!
